# This is the main build configuration for Netlify
[build]
  # This is the command Netlify will run to build your site.
  command = "hugo"
  # This is the folder Netlify will publish after the build is successful.
  publish = "public"

# This section tells Netlify which software versions to use.
[build.environment]
  # This is the crucial part. We are telling Netlify to use a specific, recent version of Hugo.
  HUGO_VERSION = "0.125.7"
  # We can also specify the Go programming language version, which Hugo is built with.
  GO_VERSION = "1.21.0"